Catkin-ProjectName: std_msgs
Version: 0.4.1
Description: Standard ROS Message

Depends: catkin, genmsg, langs, roscpp_core
Author: Morgan Quigley/mquigley@cs.stanford.edu, Ken Conley/kwc@willowgarage.com, Jeremy Leibs/leibs@willowgarage.com
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org/wiki/std_msgs

Catkin-DebRulesType: cmake
Catkin-CopyrightType:  willowgarage

Release-Pull: git://github.com/wg-debs/std_msgs.git
Release-Push: git@github.com:wg-debs/std_msgs.git

